### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by misnuge** [interledger/five-bells-wallet#28]
Good morning.

I tried to install five-bells-wallet on Ubuntu 16.04, but it won't. 

npm ERR! git clone --template=/home/m****/.npm/_git-remotes/_templates --mirror git@github.com:interledger/js-ilp-plugin-bells-admin.git /home/m****/.npm/_git-remotes/git-github-com-interledger-js-ilp-plugin-bells-admin-git-e12e5d63: 간략한 저장소로('/home/m****/.npm/_git-remotes/git-github-com-interledger-js-ilp-plugin-bells-admin-git-e12e5d63') 복제합니다...
npm ERR! git clone --template=/home/m****/.npm/_git-remotes/_templates --mirror git@github.com:interledger/js-ilp-plugin-bells-admin.git /home/m****/.npm/_git-remotes/git-github-com-interledger-js-ilp-plugin-bells-admin-git-e12e5d63: ERROR: Repository not found.
npm ERR! git clone --template=/home/m****/.npm/_git-remotes/_templates --mirror git@github.com:interledger/js-ilp-plugin-bells-admin.git /home/m****/.npm/_git-remotes/git-github-com-interledger-js-ilp-plugin-bells-admin-git-e12e5d63: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/m****/.npm/_git-remotes/_templates --mirror git@github.com:interledger/js-ilp-plugin-bells-admin.git /home/m****/.npm/_git-remotes/git-github-com-interledger-js-ilp-plugin-bells-admin-git-e12e5d63: 
npm ERR! git clone --template=/home/m****/.npm/_git-remotes/_templates --mirror git@github.com:interledger/js-ilp-plugin-bells-admin.git /home/m****/.npm/_git-remotes/git-github-com-interledger-js-ilp-plugin-bells-admin-git-e12e5d63: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/m****/.npm/_git-remotes/_templates --mirror git@github.com:interledger/js-ilp-plugin-bells-admin.git /home/m****/.npm/_git-remotes/git-github-com-interledger-js-ilp-plugin-bells-admin-git-e12e5d63: and the repository exists.
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code 128
npm ERR! Command failed: git clone --template=/home/m****/.npm/_git-remotes/_templates --mirror git@github.com:interledger/js-ilp-plugin-bells-admin.git /home/m****/.npm/_git-remotes/git-github-com-interledger-js-ilp-plugin-bells-admin-git-e12e5d63
npm ERR! 간략한 저장소로('/home/m****/.npm/_git-remotes/git-github-com-interledger-js-ilp-plugin-bells-admin-git-e12e5d63') 복제합니다...
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

--

Please check that js-ilp-plugin-bells-admin exists.

Many thanks,

misnuge

**Comment by vhpoet** [comment]
@misnuge the wallet should be working now. The repo was private.
